services:
  file-server:
    image: "server:0.1"
    build:
      context: ./
      dockerfile: ./server/deploy/Dockerfile
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.01"
          memory: "300M"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-server.rule=PathPrefix(`/`)"
      - "traefik.http.routers.file-server.middlewares=fs-deny-ip@http,fs-rate-limit@http"

  controller:
    image: "controller:0.1"
    build:
      context: ./
      dockerfile: ./controller/deploy/Dockerfile
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "6041:6041"

  metrics:
    image: prom/prometheus:v2.53.2
    user: "0:0"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - file-server
      - gateway

  gateway:
    image: traefik:v3.1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml"
      - "./traefik.yml:/etc/traefik/traefik.yml"
    ports:
      - "4000:80" # Expose traffic
      - "8080:8080" # Dashboard
    depends_on:
      - controller