services:
  file-server:
    image: "server:0.1"
    build:
      context: ./
      dockerfile: ./server/deploy/Dockerfile
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-server.rule=PathPrefix(`/`)"
      - "traefik.http.routers.file-server.middlewares=fs-deny-ip@file,fs-rate-limit@file"

  metrics:
    image: prom/prometheus:v2.53.2
    user: "0:0"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - file-server
      - gateway

  gateway:
    image: traefik:v3.1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml"
    ports:
      - "4000:80" # Expose traffic
      - "8080:8080" # Dashboard
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
      - "--providers.file.watch=true"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.forwardedHeaders.insecure=true"
      - "--experimental.plugins.denyip.modulename=github.com/kevtainer/denyip"
      - "--experimental.plugins.denyip.version=v1.0.0"