global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'file-server'
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"

    metrics_path: /metrics
    scheme: http

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: .*file-server.*
        action: keep
      - source_labels: [__meta_docker_network_ip]
        target_label: __address__
        replacement: "$1:8080"
