http:
  middlewares:
    fs-rate-limit:
      rateLimit:
        average: 7
        burst: 7
        period: 1
        sourceCriterion:
          ipStrategy:
            depth: 1
    fs-deny-ip:
      plugin:
        denyip:
          ipDenyList:
            - 24.0.0.0/8
