entryPoints:
  http:
    address: ":80"
    forwardedHeaders:
      insecure: true

api:
  insecure: true
providers:
  swarm:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true
  http:
    endpoint: http://controller:6041/gateway


metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    headerLabels:
      ip: X-Forwarded-For

experimental:
  plugins:
    denyip:
      moduleName: github.com/kevtainer/denyip
      version: v1.0.0
